---
keys:
  - &nick age13g8vu0uypup5ulq059xrs0gh4nkecvhhpkqmjdp3gpuc4w8q9c4sjys65q
  - &nicks-pc age1rcqesxqjdnhg4vz5t7f2dej0zp6s62mdmza0tucr48tvu09q5paqs4e9z6
creation_rules:
  - path_regex: \.sops\.ya?ml
    key_groups:
      - age:
          - *nick
          - *nicks-pc
